environment: 'dev'

dev:
    name: 'Intensive space'
    description: ''
    url: 'http://localhost:8888/'
    database:
        username: 'root'
        password: 'root'
        name: 'space'
        host: 'localhost'
        type: 'mysql'
    debug: true
    twig:
        cache: false
    salt: '987k(dO9dj'
    mail:
        from: 'root@root.com'
        host: 'localhost'
        username: null
        password: null
        port: 1025
    api_key: 's8VS1TaC9yWQv7jUZdPHBFKkq9OPdGv25skdu4u3'

noe:
    name: 'Intensive space'
    description: ''
    url: 'http://localhost/H2/Dev/22-intensive-space/intensive-space/public/'
    database:
        username: 'root'
        password: 'root'
        name: 'intensive-space'
        host: 'localhost'
        type: 'mysql'
    debug: true
    twig:
        cache: false
    salt: '987k(dO9dj'
    mail:
        from: 'root@root.com'
        host: 'localhost'
        username: null
        password: null
        port: 1025
    api_key: 's8VS1TaC9yWQv7jUZdPHBFKkq9OPdGv25skdu4u3'
